language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

env:
  - PHPUNIT=5.0.* COMPOSER_OPTS="--prefer-lowest"
  - PHPUNIT=5.1.*
  - PHPUNIT=5.2.*
  - PHPUNIT=5.3.*
  - PHPUNIT=5.4.*
  - PHPUNIT=5.5.*
  - PHPUNIT=5.6.*
  - PHPUNIT=5.7.*
  - PHPUNIT=6.0.*
  - PHPUNIT=6.1.*
  - PHPUNIT=6.2.*
  - PHPUNIT=6.3.*
  - PHPUNIT=6.4.*
  - PHPUNIT=6.5.*

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer require phpunit/phpunit:${PHPUNIT} ${COMPOSER_OPTS}
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - ./bin/phpchunkit --exclude-group=functional --parallel=2 --num-chunks=4 --verbose --debug
  - ./bin/phpchunkit --group=functional --sandbox --create-dbs --parallel=2 --num-chunks=4 --verbose --debug

git:
  depth: 1
